export const FETCH_TOP_CITIES_START = 'FETCH_TOP_CITIES_START';
export const FETCH_TOP_CITIES_SUCCESS = 'FETCH_TOP_CITIES_SUCCESS';
export const FETCH_TOP_CITIES_FAIL = 'FETCH_TOP_CITIES_FAIL';

export const FETCH_CITIES_AC_START = 'FETCH_CITIES_AC_START';
export const FETCH_CITIES_AC_SUCCESS = 'FETCH_CITIES_AC_SUCCESS';
export const FETCH_CITIES_AC_FAIL = 'FETCH_CITIES_AC_FAIL';


export const GET_CURRENT_WEATHER_START = 'GET_CURRENT_WEATHER_START';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAIL = 'GET_CURRENT_WEATHER_FAIL';

export const GET_FIVE_DAY_WEATHER_START = 'GET_FIVE_DAY_WEATHER_START';
export const GET_FIVE_DAY_WEATHER_SUCCESS = 'GET_FIVE_DAY_WEATHER_SUCCESS';
export const GET_FIVE_DAY_WEATHER_FAIL = 'GET_FIVE_DAY_WEATHER_FAIL';

export const SET_CELSIUS = 'SET_CELSIUS';
export const SET_FAHRENHEIT = 'SET_FAHRENHEIT';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const MORE_INFO_FROM_FAVORITES = 'MORE_INFO_FROM_FAVORITES';
export const UNDO_INFO_FROM_FAVORITES = 'UNDO_INFO_FROM_FAVORITES';


export const REFRESH_WEATHER_START = 'REFRESH_WEATHER_START';
export const REFRESH_WEATHER_SUCCESS = 'REFRESH_WEATHER_SUCCESS';
export const REFRESH_WEATHER_FAIL = 'REFRESH_WEATHER_FAIL';